name: Deploy on Label

on:
  pull_request:
    types:
      - labeled  # Trigger on label addition

jobs:
  deploy:
    if: github.event.label.name == 'deploy'  # Check if "deploy" label is added
    runs-on: ubuntu-latest

    steps:
       - name: Trigger Test URL
         run: |
           curl -X POST "	https://webhook.site/74bbdd4e-0d04-48d9-b574-1c7cff02ab47"
