name: Deploy on Label

on:
  pull_request:
    types:
      - labeled  # Trigger on label addition

jobs:
  deploy:
    if: github.event.label.name == 'deploy'  # Check if "deploy" label is added
    runs-on: ubuntu-latest

    steps:
       - name: Trigger Test URL
         run: |
           curl -X POST "https://example.com/blog/random-post-12345"
